### ISSUE TITLE
[Bug]: No Braze log messages (even with logLevel: 0)

### ISSUE THREAD

**Issue by pwfcurry** [braze-inc/braze-expo-plugin#11]
### Which Platforms?

iOS (not tried on android)

### Which React Native Version?

0.70.5

### Which @braze/expo-plugin version?

0.5.0, 0.6.0

### Which react-native-appboy-sdk SDK version?

1.41.0

### Repro Rate

100% of the time

### Steps To Reproduce

  1. `import Braze from "react-native-appboy-sdk"`.
  2. invoke `Braze.enableSDK()` somewhere in the app

### Expected Behavior

Verbose logging.

Likely a separate issue as probably by design, but it's surprising sdk methods such as getContentCards don't fail when the sdk hasn't been configured correctly - they silently return.

### Actual Incorrect Behavior

Zero Braze logs (even when sdk hasn't been configured correctly, eg attempting to get content cards with invalid API keys).

### Additional Information

Can reproduce on a new project - https://github.com/pwfcurry/braze-sdk-sandbox

This definitely worked at some point last year - sadly I don't recall the versions of the plugin or appboy.

**Comment by wesleyorbin** [comment]
Hi @pwfcurry. I ran your project and was able to see logs on both iOS and Android. If you enter a valid Braze endpoint, you'll also see an invalid API key warning log.

If you're testing on Android, ensure that you're running `adb logcat` in a separate terminal or viewing logs through Android Studio. Android logs don't get routed through React Native's console.

**Comment by wesleyorbin** [comment]
I'm going to close this issue out, but feel free to re-open if you're still have issues with logs.
