### ISSUE TITLE
[Bug]: expo prebuild not working

### ISSUE THREAD

**Issue by steunobravo** [braze-inc/braze-expo-plugin#14]
### Which Platforms?

Both

### Which React Native Version?

0.68.2

### Which @braze/expo-plugin version?

1.0.1

### Which @braze/react-native-sdk SDK version?

2.1.0

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. `expo prebuild`.
  

### Expected Behavior

Should install and synch the configuration native, so should be create the ios and android folders.

### Actual Incorrect Behavior

Show the following errors:
`Cannot find module 'expo/config-plugins'`

### Verbose Logs

```shell
Cannot find module 'expo/config-plugins'
Require stack:  
/...../node_modules/@braze/expo-plugin/build/withBraze.js
- /......./node_modules/@braze/expo-plugin/app.plugin.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/build/index.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config/build/Config.js
- /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config/build/index.js
- /opt/homebrew/lib/node_modules/expo-cli/build/utils/migration.js
- /opt/homebrew/lib/node_modules/expo-cli/build/commands/eject/prebuildAsync.js
- /opt/homebrew/lib/node_modules/expo-cli/build/commands/eject/prebuild.js
- /opt/homebrew/lib/node_modules/expo-cli/build/commands/index.js
- /opt/homebrew/lib/node_modules/expo-cli/build/exp.js
- /opt/homebrew/lib/node_modules/expo-cli/bin/expo.js
```

### Additional Information

Part of my package.jso:
"dependencies": {  
    "@braze/expo-plugin": "^1.0.1",  
    "@braze/react-native-sdk": "^2.1.0",  
    "@expo/config-plugins": "^4.1.0",  
    "expo": "^45.0.0",  
    "react": "17.0.2",  
    "react-native": "0.68.2",  
    "react-native-config": "^1.5.0",  
  },  
  
part of my app.config.js:  
plugins: [  
      [  
        '@braze/expo-plugin',  
        {  
          androidApiKey: 'APIKEY',  
          iosApiKey: 'APIKEY,  
          baseUrl: 'baseUrl',  
        },  
      ],  
    ],

**Comment by wesleyorbin** [comment]
Hi @steunobravo. What version of Expo are you on? Versions >=0.6.0 of the plugin are only compatible with Expo 47+ due to breaking changes in 47.

**Comment by steunobravo** [comment]
Hi @wesleyorbin. My version of Expo is 45. So should I update the version of Expo? Is there no other way to make it work?

**Comment by steunobravo** [comment]
Ok thanks for the advice, I'm trying to change the imports but now he is giving me problems with the cocoapods:  
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "ExpoAdapterBraze":
  In Podfile:
    ExpoAdapterBraze (from `../node_modules/@braze/expo-plugin/ios`)  


Some advice ?

**Comment by wesleyorbin** [comment]
I'm guessing you have to lower the [iOS deployment target](https://github.com/braze-inc/braze-expo-plugin/blob/main/plugin/ios/ExpoAdapterBraze.podspec#L13) to match the rest of your project. Expo 47 raised the deployment target to iOS 13.

**Comment by steunobravo** [comment]
Yes, in fact, I saw and I put that of 45 which would be 12 and the app was Builded! A thousand thanks 🎉 💣

**Comment by steunobravo** [comment]
Sorry again, I saw that in iOS it works.In Android I have this error:  
BUILD FAILED in 1m 34s
718 actionable tasks: 718 executed

/......../android/gradlew exited with non-zero code: 1
Error: /......./android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:28)
    at assembleAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:22)

**Comment by wesleyorbin** [comment]
If you scroll up from that error, do you see anything about what caused the failure?

**Comment by wesleyorbin** [comment]
I'm not sure that this issue is caused by our plugin. The expo-eas-client package has a [changelog note](https://github.com/expo/expo/blob/main/packages/expo-eas-client/CHANGELOG.md) about removing the `kotlin-android-extensions` in 0.4.1. However, the version before that raised the iOS deployment target to 13. It may be worth upgrading your Expo version, especially since they dropped support for Expo 45 with the release of Expo 48.

**Comment by steunobravo** [comment]
Ok! Thank you for support
