### ISSUE TITLE
[Bug]: Deeplinks not working with push notification on iOS when app is closed

### ISSUE THREAD

**Issue by imAliAzhar** [braze-inc/braze-expo-plugin#15]
### Which Platforms?

iOS

### Which React Native Version?

react-native

### Which @braze/expo-plugin version?

^1.0.0

### Which @braze/react-native-sdk SDK version?

^2.0.2

### Repro Rate

100%

### Steps To Reproduce

1. Quit the app.
2. Send notification with deep link.
3. `Braze.getInitialURL` returns null.

### Expected Behavior

`Braze.getInitialURL` should return the deep link sent with the notification.

### Actual Incorrect Behavior

`Braze.getInitialURL` returns null.

### Additional Information

This issue has been reported on the [braze-inc/braze-react-native-sdk ](https://github.com/braze-inc/braze-react-native-sdk) before multiple times:
- [Notification on click Deep Link into Application does not work #152](https://github.com/braze-inc/braze-react-native-sdk/issues/152)
- [Deep link invocation when app is in quit state on iOS is not working #145](https://github.com/braze-inc/braze-react-native-sdk/issues/145)
- [Deeplinks not working from push notification action buttons on iOS when app is closed #103](https://github.com/braze-inc/braze-react-native-sdk/issues/103)

But the issue still persists when using this Expo config plugin.

**Comment by wesleyorbin** [comment]
Hi @imAliAzhar. Thanks for bringing this to our attention and for the PR. We'll have a fix out for this soon.

**Comment by wesleyorbin** [comment]
Hi @imAliAzhar. We just released this fix in v1.1.1. Thanks again for bringing this to our attention!
