### ISSUE TITLE
[Bug]:  Expo SDK 50 iOS Braze methods not firing

### ISSUE THREAD

**Issue by josh-the-dev** [braze-inc/braze-expo-plugin#28]
### Which Platforms?

iOS

### Which React Native Version?

0.73.2

### Which @braze/expo-plugin version?

1.2.0

### Which @braze/react-native-sdk SDK version?

8.3.0

### Repro Rate

100%

### Steps To Reproduce

  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  3. Run the app on an iOS device. 

### Expected Behavior

I would expect to check in Braze and see the user with ID ("id") be queryable and see their user profile in Braze. 

### Actual Incorrect Behavior

When I query in Braze for the user with ID ("id") it says that there is no user found.

### Additional Information

**NOTE** Downgraded Expo to 49 and it seems to work. So definitely believe this is to do with Expo SDK V50, curious what could have broke this.

This is a new Expo app we have and the first plugin we're using is Braze. We have followed the docs to the letter. As I say it works on the prior SDK version with Expo, so curious what has changed in 50 to break this functionality.

Android works completely fine.

**Comment by jerielng** [comment]
Hey @josh-the-dev, it looks like in Expo 50, the `BrazeAppDelegate` isn't being registered due to some breaking changes in how `appDelegateSubscribers` are recognized, and so the Braze plugin isn't being initialized.

There isn't a whole lot of documentation around this breaking change, but we'll take a deeper look and keep you updated. If there are any changes required in the Braze plugin, we'll aim to bundle those into our release containing some of the new Android Gradle updates.

**Comment by josh-the-dev** [comment]
Hey there!

Thanks for the quick update on this. Ah I was curious how Expo 50 had a breaking change on this... that's really insightful. Makes perfect sense and glad you and the team are on top of it, thanks for the response.

I guess this issue can close when the appropriate work is implemented? Because we'd rather avoid downgrading unless absolutely required.

**Comment by jerielng** [comment]
At the moment, I can't say for certain what the breaking change is and whether the fix will involve updating a configuration within your own app or within our plugin, but we'll let you know when we have a working solution and will close out the issue at that point. Thanks!

**Comment by jerielng** [comment]
Hey @josh-the-dev, just a quick update here: I filed a [bug report](https://github.com/expo/expo/issues/26805) with the Expo team, and it looks like there is a bug on their end with Expo SDK 50. There's currently a fix in progress from their end, which you can track [here](https://github.com/expo/expo/pull/26851).

**Comment by josh-the-dev** [comment]
Hey @jerielng really appreciate the update! Makes perfect sense, in that case I guess we wait til Expo patch it, and then we do any remedial action from there?

**Comment by jerielng** [comment]
@josh-the-dev, yep that's correct! I don't believe you will need to make any changes other than bumping to the patch version, but I imagine it should work as it did before in Expo 49.

**Comment by jerielng** [comment]
Hey @josh-the-dev, it looks like there's a fix available now in Expo `50.0.6`, so you should be able to upgrade to that version! I will close out this issue now, but feel free to open a new one if you have additional questions. Thanks!

**Comment by josh-the-dev** [comment]
Thanks so much for the update @jerielng , will be sure to try that and let you know if that works.
