### ISSUE TITLE
Compatibility Expo SDK 47

### ISSUE THREAD

**Issue by christophe-chausseray** [braze-inc/braze-expo-plugin#3]
Since Expo SDK 47 was released, the minimum `deployment target` needed for iOS is 13.

The current platform version defined in the [ExpoAdapterBraze.podspec](https://github.com/braze-inc/braze-expo-plugin/blob/main/plugin/ios/ExpoAdapterBraze.podspec) is 12. It makes impossible to install this plugin on a project with Expo SDK 47 without having this error :
```

compiling for iOS 12.0, but module 'ExpoModulesCore' has a minimum deployment target of iOS 13.0
```

Would it be possible to upgrade the platform version in the podspec from 12 to 13 ?

**Comment by wesleyorbin** [comment]
Hi @christophe-chausseray. We just released 0.5.0, which updates the minimum deployment target to 13.0. Please let us know if you encounter any issues after upgrading.
