### ISSUE TITLE
[Bug]: eas build error "com.apple.security.application-groups" has invalid value "$(BRAZE_PUSH_STORY_APP_GROUP)".

### ISSUE THREAD

**Issue by mmoussel** [braze-inc/braze-expo-plugin#33]
### Which Platforms?

iOS

### Which React Native Version?

0.74.5

### Which @braze/expo-plugin version?

3.0.0

### Which @braze/react-native-sdk SDK version?

13.1.1

### Repro Rate

100

### Steps To Reproduce

add this configuration in app.config.js
`{
          "enableBrazeIosPushStories": true,
          "iosPushStoryAppGroup": process.env.BRAZE_IOS_PUSH_STORY_APP_GROUP
 }`

### Expected Behavior

build the app successfully

### Actual Incorrect Behavior

after running `eas build --platform ios --profile development`
I'm getting this error "com.apple.security.application-groups" has invalid value "$(BRAZE_PUSH_STORY_APP_GROUP)"

### Verbose Logs

```shell
✖ Failed to sync capability identifiers com.****
iOS entitlement "com.apple.security.application-groups" has invalid value "$(BRAZE_PUSH_STORY_APP_GROUP)". Expected an array of strings, where each string is prefixed with "group.", ex: ["group.myapp"]
    Error: build command failed.
error Command failed with exit code 1.
```

### Additional Information

i'm sure BRAZE_IOS_PUSH_STORY_APP_GROUP is successfully gets read and also I tried to put it static

also when I change enableBrazeIosPushStories to false it build successfully 
also when I add the value static in `BrazeExpoPushStories.entitlements` file  it build successfully

**Comment by hokstuff** [comment]
Hi @mmoussel,

The name `BRAZE_PUSH_STORY_APP_GROUP` does not match anything in our codebase and should be replaced with the actual identifier used by your Push Stories App Group, [as noted in our instructions here](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/push_notifications/push_story/#adding-an-app-group). Additionally, [this tutorial](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b3-push-stories) shows how to integrate Push Stories into a native iOS application. To see a working Expo example, you can reference our sample app code [here](https://github.com/braze-inc/braze-expo-plugin/blob/797aa4fed8b7d3bc044c7bd12b9b4401a6f0640e/example/app.json#L68) and open the sample app in Xcode to see the string that it matches.

If you have further issues, please contact support@braze.com to work with the Support team to debug your specific setup. They will ask for integration code and point you to our public documentation to make sure nothing was missed.

Thanks!
