### ISSUE TITLE
[Feature]: Custom notification sound support

### ISSUE THREAD

**Issue by jacobhummel** [braze-inc/braze-expo-plugin#7]
### What problem are you facing?

The only thing stopping me from using this plugin is lack of support for custom sounds. Let me know if I am mistaken and this is supported!

### Workarounds

None that I am aware of

### Ideal Solution

Expo Notifications supports custom sounds like this: https://docs.expo.dev/versions/latest/sdk/notifications/#example-appjson-with-config-plugin

```json
{
  "expo": {
    "plugins": [
      [
        "expo-notifications",
        {
          "icon": "./local/assets/notification-icon.png",
          "color": "#ffffff",
          "sounds": [
            "./local/assets/notification-sound.wav",
            "./local/assets/notification-sound-other.wav"
          ]
        }
      ]
    ]
  }
}
```

**Comment by wesleyorbin** [comment]
Hi @jacobhummel. Notification sounds are supported by uploading the audio file when composing the push notification on the Braze dashboard. See our docs for [iOS](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/customization/custom_sounds#custom-sounds) and [Android](https://www.braze.com/docs/user_guide/message_building_by_channel/push/android/advanced_campaign_settings/#notification-sounds). Let me know if this works for you when using our plugin.

**Comment by jacobhummel** [comment]
Thanks for the quick reply @wesleyorbin! It does look like there is custom sound support, but that does not work with the Expo plugin since the Expo plugin would need to allow the custom sound files as input for the prebuild step. I posted an example of how `expo-notifications` allows this with their `sounds` parameter.

**Comment by wesleyorbin** [comment]
@jacobhummel I've filed a ticket internally to investigate adding a `sounds` prop. While iOS only requires copying the files into the Xcode project, Android looks to be more involved and will likely require some work on either the Android or React Native SDK. I'll keep you posted here with any updates.

**Comment by jacobhummel** [comment]
@wesleyorbin thank you! Currently my Expo project is only deployed to the App Store, so iOS only support may not be a bad start for some users! :)

**Comment by wesleyorbin** [comment]
Hi @jacobhummel. Apologies for the delay. We looked into adding native support for custom sounds, but found that using `expo-notifications` to copy the sound files over works just as well. Adding it to your project and setting the `sounds` prop in your `app.json` will copy the files into the correct places. I've verified on iOS that this works with the Braze SDK.
